### PR TITLE
Clarify supported versions in README.md

### PR DESCRIPTION
**Pull request by catfromplan9**

### CODE REVIEW

**Comment by evan-goode** [comment]
Nice, would you mind testing a 1.6 server with Drasl just to make sure it works (if you haven't already)?

**Comment by catfromplan9** [comment]
> Nice, would you mind testing a 1.6 server with Drasl just to make sure it works (if you haven't already)?

I stand corrected, authentication begins working on the first version of 1.7, that being 1.7.2. 1.6.x returns "Bad login."

Capes are broken on 1.6-1.7.5 but were fixed in 1.7.6, see related changelog entry:
> Skins and capes are now distributed through servers.

**Comment by catfromplan9** [comment]
Well, 1.6.4 has none of the new authentication (http://session.minecraft.net and http://skins.minecraft.net are used). This is strange because the Minecraft wiki says 1.6.1 was when yggdrasil support was added to the launcher implying clients supported it too. There's nothing on the 1.7.2 wiki page regarding yggdrasil but nonetheless that is when yggdrasil was actually switched to.

**Comment by evan-goode** [comment]
Thanks for checking, yeah 1.7 sounds more correct to me.

**Pull request merged**
